# Generated by Django 6.1.1 on 2026-09-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('hour', models.IntegerField()),
                ('distance_km', models.FloatField()),
                ('device_score', models.FloatField()),
                ('international', models.BooleanField()),
                ('merchant_risk', models.FloatField()),
                ('high_amount', models.BooleanField(default=False)),
                ('night_transaction', models.BooleanField(default=False)),
                ('unusual_distance', models.BooleanField(default=False)),
                ('low_device_trust', models.BooleanField(default=False)),
                ('high_merchant_risk', models.BooleanField(default=False)),
                ('fraud_probability', models.FloatField()),
                ('prediction', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
